import { CheckCircle2, ChevronLeft, ChevronRight, ClipboardCheck, RotateCcw, Sparkles, Trophy } from "lucide-react";
import { useMemo, useState } from "react";

type Analysis={atsScore:number;matchPercentage:number;missingKeywords:string[];strengths:string[];improvements:string[];jobTitle?:string|null};
type Props={analysis:Analysis|null;dark?:boolean};
type Question={category:string;question:string};
type Feedback={score:number;clarity:number;relevance:number;structure:number;strength:string;improvement:string};

const questionBank=(analysis:Analysis):Question[]=>[
 {category:"Introduction",question:`Tell me about yourself and why you are interested in ${analysis.jobTitle||"this role"}.`},
 {category:"Experience",question:"Describe a project or experience that best demonstrates your ability to solve problems."},
 {category:"Technical",question:`How would you apply the skills most important for ${analysis.jobTitle||"this role"} in a real project?`},
 {category:"Behavioral",question:"Tell me about a time you faced a difficult challenge and how you handled it."},
 {category:"Gap",question:analysis.missingKeywords.length?`Your resume has a gap around ${analysis.missingKeywords[0]}. How are you building capability in this area?`:"What skill are you currently improving, and what is your plan for it?"},
];
function evaluate(answer:string,q:Question):Feedback{
 const words=answer.trim().split(/\s+/).filter(Boolean);const length=words.length;
 const sentences=answer.split(/[.!?]+/).map(x=>x.trim()).filter(Boolean).length;
 const lower=answer.toLowerCase();
 const structureSignals=["situation","task","action","result","because","therefore","first","then","finally"];
 const structureCount=structureSignals.filter(x=>lower.includes(x)).length;
 const clarity=Math.min(100,Math.round(45+Math.min(length,90)*0.35+Math.min(sentences,6)*4));
 const relevanceHints=q.category==="Technical"?["built","implemented","tested","debug","design","api","database","project","code"]:["project","experience","team","result","learned","solved","improved","challenge"];
 const relevanceHits=relevanceHints.filter(x=>lower.includes(x)).length;
 const relevance=Math.min(100,Math.round(48+relevanceHits*7+Math.min(length,70)*0.25));
 const structure=Math.min(100,Math.round(48+structureCount*7+Math.min(sentences,5)*4));
 const score=Math.round(clarity*0.3+relevance*0.45+structure*0.25);
 return {score,clarity,relevance,structure,strength:length>=35?"You gave enough detail to support a useful answer.":"You started with the core idea; adding more evidence would make the answer stronger.",improvement:score>=80?"Tighten the answer further by leading with the result and keeping only the strongest evidence.":score>=65?"Add a concrete example and measurable outcome, then close with what you learned.":"Use a simple structure: situation → action → result. Stay focused on your own contribution."};
}

export default function AIMockInterview({analysis,dark=false}:Props){
 const questions=useMemo(()=>analysis?questionBank(analysis):[],[analysis]);
 const [started,setStarted]=useState(false); const [index,setIndex]=useState(0); const [answer,setAnswer]=useState("");
 const [feedback,setFeedback]=useState<Feedback|null>(null); const [scores,setScores]=useState<Feedback[]>([]);
 if(!analysis||!questions.length)return null;
 const text=dark?"#e5e7eb":"#0f172a",muted=dark?"#94a3b8":"#64748b",border=dark?"#334155":"#e2e8f0",bg=dark?"rgba(15,23,42,.86)":"#fff";
 const completed=scores.length>=questions.length;
 const submit=()=>{if(!answer.trim())return;const next=evaluate(answer,questions[index]);setFeedback(next);setScores(prev=>{const copy=[...prev];copy[index]=next;return copy;});};
 const next=()=>{setAnswer("");setFeedback(null);setIndex(i=>Math.min(i+1,questions.length-1));};
 const reset=()=>{setStarted(false);setIndex(0);setAnswer("");setFeedback(null);setScores([]);};
 const overall=scores.length?Math.round(scores.reduce((s,x)=>s+x.score,0)/scores.length):0;
 if(!started)return <section style={{padding:24,borderRadius:24,border:`1px solid ${border}`,background:bg,boxShadow:"0 18px 50px rgba(15,23,42,.06)"}}><div style={{display:"flex",alignItems:"center",gap:8,color:"#7c3aed"}}><ClipboardCheck size={20}/><strong>AI mock interview</strong></div><h2 style={{margin:"8px 0 6px",color:text}}>Practice before the real interview</h2><p style={{color:muted,lineHeight:1.6}}>Answer {questions.length} role-focused questions one at a time and receive a structured practice score. This is coaching feedback, not a prediction of interview outcomes.</p><button onClick={()=>setStarted(true)} style={{marginTop:10,border:0,borderRadius:13,background:"linear-gradient(135deg,#7c3aed,#2563eb)",color:"white",padding:"13px 18px",cursor:"pointer",fontWeight:800,display:"inline-flex",alignItems:"center",gap:8}}><Sparkles size={17}/>Start mock interview</button></section>;
 if(completed)return <section style={{padding:24,borderRadius:24,border:`1px solid ${border}`,background:bg}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",gap:12,flexWrap:"wrap"}}><div><div style={{display:"flex",alignItems:"center",gap:8,color:"#7c3aed"}}><Trophy size={20}/><strong>Mock interview complete</strong></div><p style={{margin:"7px 0 0",color:muted}}>Practice performance across all questions.</p></div><button onClick={reset} style={{border:`1px solid ${border}`,borderRadius:11,background:bg,color:text,padding:"9px 12px",cursor:"pointer",display:"inline-flex",gap:7,alignItems:"center"}}><RotateCcw size={15}/>Start over</button></div><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(170px,1fr))",gap:12,marginTop:18}}><Metric label="Overall practice score" value={`${overall}/100`} dark={dark}/><Metric label="Questions answered" value={`${scores.length}/${questions.length}`} dark={dark}/><Metric label="Strongest dimension" value={strengthest(scores)} dark={dark}/></div><div style={{marginTop:16,padding:16,borderRadius:16,background:"rgba(124,58,237,.08)",color:muted,lineHeight:1.6}}>Use the lowest-scoring dimension as your next practice target. Strong answers should be specific, relevant, and outcome-focused.</div></section>;
 return <section style={{padding:24,borderRadius:24,border:`1px solid ${border}`,background:bg}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",gap:12}}><div><div style={{fontSize:12,fontWeight:800,color:"#7c3aed",letterSpacing:".06em"}}>MOCK INTERVIEW</div><div style={{marginTop:5,fontSize:13,color:muted}}>Question {index+1} of {questions.length}</div></div><button onClick={reset} style={{border:`1px solid ${border}`,borderRadius:11,background:bg,color:text,padding:"8px 11px",cursor:"pointer"}}><RotateCcw size={15}/></button></div><div style={{marginTop:16,padding:18,borderRadius:18,background:dark?"rgba(30,41,59,.55)":"#f8fafc"}}><div style={{fontSize:11,fontWeight:800,color:"#7c3aed",textTransform:"uppercase"}}>{questions[index].category}</div><h3 style={{margin:"7px 0 0",color:text,lineHeight:1.5}}>{questions[index].question}</h3></div><textarea value={answer} onChange={e=>setAnswer(e.target.value)} disabled={!!feedback} placeholder="Type your interview answer here..." style={{width:"100%",minHeight:170,marginTop:14,padding:14,boxSizing:"border-box",resize:"vertical",font:"inherit",borderRadius:14,border:`1px solid ${border}`,background:dark?"#020617":"#fff",color:text}}/><div style={{display:"flex",justifyContent:"space-between",gap:12,marginTop:10,flexWrap:"wrap"}}><span style={{fontSize:12,color:muted}}>{answer.trim()?answer.trim().split(/\s+/).length:0} words</span><button onClick={submit} disabled={!answer.trim()||!!feedback} style={{border:0,borderRadius:11,background:"linear-gradient(135deg,#7c3aed,#2563eb)",color:"white",padding:"10px 14px",cursor:"pointer",fontWeight:800,opacity:feedback?0.55:1}}>Evaluate answer</button></div>{feedback&&<div style={{marginTop:18,border:`1px solid ${border}`,borderRadius:18,padding:18}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",gap:12}}><div><div style={{fontSize:12,color:muted}}>Practice score</div><strong style={{fontSize:34,color:feedback.score>=80?"#15803d":feedback.score>=65?"#d97706":"#dc2626"}}>{feedback.score}/100</strong></div><div style={{textAlign:"right",fontSize:12,color:muted}}>Clarity {feedback.clarity}%<br/>Relevance {feedback.relevance}%<br/>Structure {feedback.structure}%</div></div><div style={{marginTop:14}}><strong style={{fontSize:12,color:muted}}>What worked</strong><p style={{color:text,lineHeight:1.55}}>{feedback.strength}</p><strong style={{fontSize:12,color:muted}}>Improve next</strong><p style={{marginBottom:0,color:text,lineHeight:1.55}}>{feedback.improvement}</p></div><button onClick={next} disabled={index===questions.length-1} style={{marginTop:14,border:`1px solid ${border}`,borderRadius:11,background:bg,color:text,padding:"9px 12px",cursor:"pointer",display:"inline-flex",gap:7,alignItems:"center"}}>Next question <ChevronRight size={15}/></button></div>}</section>;
}
function Metric({label,value,dark}:{label:string;value:string;dark:boolean}){return <div style={{padding:16,borderRadius:16,background:dark?"rgba(30,41,59,.55)":"#f8fafc"}}><div style={{fontSize:12,color:dark?"#94a3b8":"#64748b"}}>{label}</div><strong style={{display:"block",marginTop:6,fontSize:25,color:dark?"#e5e7eb":"#0f172a"}}>{value}</strong></div>}
function strengthest(scores:Feedback[]){if(!scores.length)return "—";const totals={Clarity:scores.reduce((a,x)=>a+x.clarity,0),Relevance:scores.reduce((a,x)=>a+x.relevance,0),Structure:scores.reduce((a,x)=>a+x.structure,0)};return Object.entries(totals).sort((a,b)=>b[1]-a[1])[0][0];}
