import { useMemo, useState } from "react";
import { Download, Eye, Search, TrendingUp, X } from "lucide-react";

type Analysis={id?:string;analysisId?:string;atsScore:number;matchPercentage:number;resumeFileName?:string;jobTitle?:string|null;summary?:string;resumeText?:string;jobDescription?:string;createdAt?:string};
type Props={analyses:Analysis[];dark?:boolean;onView:(analysis:Analysis)=>void;onDownload:(analysis:Analysis)=>void};

export default function AnalysisHistory({analyses,dark=false,onView,onDownload}:Props){
 const[q,setQ]=useState("");const[sort,setSort]=useState("newest");const[min,setMin]=useState("0");
 const list=useMemo(()=>[...analyses].filter(a=>`${a.jobTitle||""} ${a.resumeFileName||""}`.toLowerCase().includes(q.toLowerCase())&&a.atsScore>=Number(min)).sort((a,b)=>sort==="highest"?b.atsScore-a.atsScore:sort==="match"?b.matchPercentage-a.matchPercentage:new Date(b.createdAt||0).getTime()-new Date(a.createdAt||0).getTime()),[analyses,q,sort,min]);
 const bg=dark?"#0f172a":"#fff";const border=dark?"#334155":"#e2e8f0";const muted=dark?"#94a3b8":"#64748b";
 return <section style={{background:bg,border:`1px solid ${border}`,borderRadius:24,padding:22,boxShadow:"0 18px 50px rgba(15,23,42,.06)"}}><div style={{display:"flex",justifyContent:"space-between",gap:12,alignItems:"center",flexWrap:"wrap"}}><div><div style={{display:"flex",gap:8,alignItems:"center"}}><TrendingUp size={19} color="#7c3aed"/><strong>Analysis history</strong></div><p style={{opacity:.6,marginBottom:0,color:muted}}>Search and prioritize your strongest resume matches.</p></div><strong style={{color:"#7c3aed"}}>{list.length} results</strong></div><div style={{display:"grid",gridTemplateColumns:"minmax(220px,1fr) 160px 140px",gap:10,marginTop:16}}><div style={{position:"relative"}}><Search size={16} style={{position:"absolute",left:12,top:12,opacity:.5}}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search role or resume..." style={input(dark)}/></div><select value={sort} onChange={e=>setSort(e.target.value)} style={input(dark)}><option value="newest">Newest</option><option value="highest">Highest ATS</option><option value="match">Best match</option></select><select value={min} onChange={e=>setMin(e.target.value)} style={input(dark)}><option value="0">All scores</option><option value="50">50%+ ATS</option><option value="75">75%+ ATS</option></select></div><div style={{display:"grid",gap:10,marginTop:16}}>{list.map(a=><div key={a.id||a.analysisId} style={{display:"flex",justifyContent:"space-between",alignItems:"center",gap:14,padding:15,border:`1px solid ${border}`,borderRadius:16,flexWrap:"wrap"}}><div><strong>{a.jobTitle||"Resume analysis"}</strong><div style={{fontSize:13,opacity:.6,marginTop:3}}>{a.resumeFileName||"Resume document"}</div></div><div style={{display:"flex",alignItems:"center",gap:9,flexWrap:"wrap"}}><span style={score}>{a.atsScore}% ATS</span><span style={match}>{a.matchPercentage}% match</span><button onClick={()=>onView(a)} style={btn(dark)}><Eye size={15}/>View</button><button onClick={()=>onDownload(a)} style={btn(dark)}><Download size={15}/>PDF</button></div></div>)}{!list.length&&<div style={{padding:28,textAlign:"center",opacity:.6}}><X size={22}/><div>No analyses match these filters.</div></div>}</div></section>}
const input=(dark:boolean):React.CSSProperties=>({width:"100%",boxSizing:"border-box",padding:"11px 12px",border:`1px solid ${dark?"#475569":"#cbd5e1"}`,borderRadius:12,font:"inherit",background:dark?"#020617":"white",color:dark?"#e5e7eb":"#0f172a"});const btn=(dark:boolean):React.CSSProperties=>({border:`1px solid ${dark?"#475569":"#d8dee9"}`,background:dark?"#0f172a":"white",color:dark?"#e5e7eb":"#0f172a",padding:"8px 10px",borderRadius:10,cursor:"pointer",display:"inline-flex",gap:6,alignItems:"center"});const score:React.CSSProperties={padding:"6px 9px",borderRadius:999,background:"rgba(124,58,237,.1)",color:"#6d28d9",fontWeight:800,fontSize:13};const match:React.CSSProperties={padding:"6px 9px",borderRadius:999,background:"rgba(34,197,94,.1)",color:"#15803d",fontWeight:800,fontSize:13};
