import { Copy, FileText, Loader2, Sparkles } from "lucide-react";
import { useState } from "react";

type Props={token:string;resumeText?:string;jobDescription?:string;targetRole?:string;dark?:boolean};
const API=import.meta.env.VITE_API_URL??"";
export default function CoverLetterGenerator({token,resumeText="",jobDescription="",targetRole="",dark=false}:Props){
 const [company,setCompany]=useState(""); const [role,setRole]=useState(targetRole); const [job,setJob]=useState(jobDescription); const [resume,setResume]=useState(resumeText); const [content,setContent]=useState(""); const [loading,setLoading]=useState(false); const [error,setError]=useState(""); const [copied,setCopied]=useState(false);
 const text=dark?"#e5e7eb":"#0f172a",muted=dark?"#94a3b8":"#64748b",border=dark?"#334155":"#e2e8f0",bg=dark?"rgba(15,23,42,.86)":"#fff";
 const generate=async()=>{setError("");if(!role.trim()||job.trim().length<30||resume.trim().length<50){setError("Add a target role, meaningful job description, and resume text first.");return;}setLoading(true);try{const r=await fetch(`${API}/api/cover-letter`,{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${token}`},body:JSON.stringify({targetRole:role,company,jobDescription:job,resumeText:resume})});const d=await r.json();if(!r.ok)throw new Error(d.error||"Unable to generate cover letter.");setContent(d.content);}catch(e){setError(e instanceof Error?e.message:"Unable to generate cover letter.");}finally{setLoading(false);}};
 const copy=async()=>{if(!content)return;await navigator.clipboard?.writeText(content);setCopied(true);window.setTimeout(()=>setCopied(false),1400);};
 return <section style={{padding:24,borderRadius:24,border:`1px solid ${border}`,background:bg,boxShadow:"0 18px 50px rgba(15,23,42,.06)"}}><div style={{display:"flex",alignItems:"center",gap:8,color:"#7c3aed"}}><FileText size={20}/><strong>AI cover letter generator</strong></div><p style={{margin:"7px 0 16px",color:muted}}>Create a tailored cover letter grounded in your resume and the job description.</p><div style={{display:"grid",gap:10}}><input value={company} onChange={e=>setCompany(e.target.value)} placeholder="Company name (optional)" style={input(dark)}/><input value={role} onChange={e=>setRole(e.target.value)} placeholder="Target role" style={input(dark)}/><textarea value={job} onChange={e=>setJob(e.target.value)} placeholder="Job description" style={{...input(dark),minHeight:130,resize:"vertical"}}/><textarea value={resume} onChange={e=>setResume(e.target.value)} placeholder="Resume text" style={{...input(dark),minHeight:150,resize:"vertical"}}/></div>{error&&<p style={{color:"#dc2626",marginBottom:0}}>{error}</p>}<button onClick={generate} disabled={loading} style={{marginTop:12,border:0,borderRadius:12,background:"linear-gradient(135deg,#7c3aed,#2563eb)",color:"white",padding:"12px 16px",cursor:"pointer",fontWeight:800,display:"inline-flex",gap:8,alignItems:"center",opacity:loading?.7:1}}>{loading?<Loader2 size={16}/>:<Sparkles size={16}/>} {loading?"Generating...":"Generate cover letter"}</button>{content&&<div style={{marginTop:18,padding:18,border:`1px solid ${border}`,borderRadius:18}}><div style={{display:"flex",justifyContent:"space-between",gap:12,alignItems:"center"}}><strong style={{color:text}}>Generated cover letter</strong><button onClick={copy} style={{border:`1px solid ${border}`,background:bg,color:text,borderRadius:10,padding:"8px 10px",cursor:"pointer",display:"inline-flex",gap:6,alignItems:"center"}}><Copy size={14}/>{copied?"Copied":"Copy"}</button></div><pre style={{whiteSpace:"pre-wrap",font:"inherit",lineHeight:1.7,color:text,margin:"14px 0 0"}}>{content}</pre></div>}</section>;
}
const input=(dark:boolean):React.CSSProperties=>({width:"100%",boxSizing:"border-box",padding:12,border:`1px solid ${dark?"#475569":"#cbd5e1"}`,borderRadius:12,background:dark?"#020617":"#fff",color:dark?"#e5e7eb":"#0f172a",font:"inherit"});
