import { useMemo, useState } from "react";
import { CheckCircle2, Circle, Flag, Gauge, ListChecks, Sparkles, Target } from "lucide-react";

type Analysis={atsScore:number;matchPercentage:number;strengths:string[];improvements:string[];missingKeywords:string[]};
type Props={analysis?:Analysis|null;dark?:boolean};
type Item={id:string;text:string;priority:"High"|"Medium"|"Completed";done:boolean};

export default function ImprovementRoadmap({analysis,dark=false}:Props){
 const initial=useMemo<Item[]>(()=>{if(!analysis)return[];return [...analysis.improvements.slice(0,4).map((text,i)=>({id:`high-${i}`,text,priority:"High" as const,done:false})),...analysis.missingKeywords.slice(0,5).map((text,i)=>({id:`medium-${i}`,text:`Add or demonstrate: ${text}`,priority:"Medium" as const,done:false})),...analysis.strengths.slice(0,3).map((text,i)=>({id:`done-${i}`,text,priority:"Completed" as const,done:true}))]},[analysis]);
 const[items,setItems]=useState<Item[]>([]); const roadmap=items.length?items:initial; const toggle=(id:string)=>setItems((items.length?items:initial).map(x=>x.id===id?{...x,done:!x.done}:x)); const completed=roadmap.filter(x=>x.done).length; const progress=roadmap.length?Math.round(completed/roadmap.length*100):0;
 const bg=dark?"#0f172a":"#fff";const border=dark?"#334155":"#e2e8f0";const muted=dark?"#94a3b8":"#64748b";
 return <section style={{marginTop:24,padding:22,borderRadius:24,border:`1px solid ${border}`,background:bg,boxShadow:"0 18px 50px rgba(15,23,42,.06)"}}><div style={{display:"flex",justifyContent:"space-between",gap:12,alignItems:"flex-start",flexWrap:"wrap"}}><div><div style={{display:"flex",gap:8,alignItems:"center",color:"#7c3aed"}}><ListChecks size={20}/><strong>Resume Improvement Roadmap</strong></div><p style={{margin:"7px 0 0",color:muted}}>Complete the highest-impact improvements step by step.</p></div><div style={{fontSize:26,fontWeight:850,color:"#7c3aed"}}>{progress}%</div></div><div style={{height:10,borderRadius:999,background:dark?"#1e293b":"#e2e8f0",overflow:"hidden",marginTop:18}}><div style={{height:"100%",width:`${progress}%`,background:"linear-gradient(90deg,#7c3aed,#2563eb)",transition:"width .25s"}}/></div><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(150px,1fr))",gap:12,marginTop:18}}><Metric icon={<Target size={17}/>} label="ATS score" value={`${analysis?.atsScore||0}%`}/><Metric icon={<Gauge size={17}/>} label="Job match" value={`${analysis?.matchPercentage||0}%`}/><Metric icon={<CheckCircle2 size={17}/>} label="Tasks completed" value={`${completed}/${roadmap.length}`}/></div><div style={{display:"grid",gap:10,marginTop:18}}>{roadmap.length?roadmap.map(item=><button key={item.id} onClick={()=>toggle(item.id)} style={{textAlign:"left",border:`1px solid ${border}`,background:dark?"rgba(30,41,59,.6)":"#fff",color:dark?"#e5e7eb":"#0f172a",borderRadius:16,padding:14,cursor:"pointer",display:"flex",alignItems:"center",gap:12}}>{item.done?<CheckCircle2 size={20} color="#22c55e"/>:<Circle size={20} color="#94a3b8"/>}<div style={{flex:1}}><div style={{fontWeight:750,textDecoration:item.done?"line-through":"none",opacity:item.done?.65:1}}>{item.text}</div><span style={{fontSize:12,color:item.priority==="High"?"#dc2626":item.priority==="Completed"?"#15803d":"#d97706",fontWeight:800}}>{item.priority} priority</span></div>{item.priority==="High"&&<Flag size={17} color="#dc2626"/>}</button>):<div style={{textAlign:"center",padding:35,color:muted}}><Sparkles size={24}/><p>Run a resume analysis to generate your personalized improvement roadmap.</p></div>}</div></section>;
}
function Metric({icon,label,value}:{icon:React.ReactNode;label:string;value:string}){return <div style={{padding:15,borderRadius:17,background:"rgba(124,58,237,.08)"}}><div style={{display:"flex",gap:7,alignItems:"center",color:"#7c3aed",fontSize:13,fontWeight:700}}>{icon}{label}</div><strong style={{fontSize:25,display:"block",marginTop:7}}>{value}</strong></div>}
