import { BriefcaseBusiness, CalendarDays, CirclePlus, Search, Trash2 } from "lucide-react";
import { useEffect, useMemo, useState } from "react";

type Status="Applied"|"Interview"|"Offer"|"Rejected";
type Application={id:string;company:string;role:string;status:Status;appliedAt:string;notes:string};
const STATUSES:Status[]=["Applied","Interview","Offer","Rejected"];
const API_URL=import.meta.env.VITE_API_URL||"http://localhost:3001";
const getToken=()=>localStorage.getItem("resumeiq_token")||localStorage.getItem("token")||"";

export default function JobApplicationTracker({dark=false}:{dark?:boolean}){
 const [applications,setApplications]=useState<Application[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState("");
 const [company,setCompany]=useState("");const [role,setRole]=useState("");const [status,setStatus]=useState<Status>("Applied");const [date,setDate]=useState(new Date().toISOString().slice(0,10));const [notes,setNotes]=useState("");
 const [query,setQuery]=useState("");const [filter,setFilter]=useState<Status|"All">("All");
 const text=dark?"#e5e7eb":"#0f172a",muted=dark?"#94a3b8":"#64748b",border=dark?"#334155":"#e2e8f0",bg=dark?"rgba(15,23,42,.86)":"#fff";
 const request=async(path:string,options:RequestInit={})=>{const token=getToken();const response=await fetch(`${API_URL}${path}`,{...options,headers:{"Content-Type":"application/json",...(token?{Authorization:`Bearer ${token}`}:{}) ,...(options.headers||{})}});if(!response.ok){const body=await response.json().catch(()=>({}));throw new Error(body.error||"Request failed.");}return response.status===204?null:response.json();};
 const load=async()=>{setLoading(true);try{const data=await request("/api/applications");setApplications(data);}catch(err){setError(err instanceof Error?err.message:"Unable to load applications.");}finally{setLoading(false);}};
 useEffect(()=>{void load();},[]);
 const add=async()=>{if(!company.trim()||!role.trim())return;try{setError("");const item=await request("/api/applications",{method:"POST",body:JSON.stringify({company:company.trim(),role:role.trim(),status,appliedAt:date,notes:notes.trim()})});setApplications(items=>[item,...items]);setCompany("");setRole("");setStatus("Applied");setDate(new Date().toISOString().slice(0,10));setNotes("");}catch(err){setError(err instanceof Error?err.message:"Unable to save application.");}};
 const updateStatus=async(id:string,next:Status)=>{try{const updated=await request(`/api/applications/${id}`,{method:"PATCH",body:JSON.stringify({status:next})});setApplications(items=>items.map(a=>a.id===id?updated:a));}catch(err){setError(err instanceof Error?err.message:"Unable to update application.");}};
 const remove=async(id:string)=>{try{await request(`/api/applications/${id}`,{method:"DELETE"});setApplications(items=>items.filter(a=>a.id!==id));}catch(err){setError(err instanceof Error?err.message:"Unable to delete application.");}};
 const filtered=useMemo(()=>{const q=query.trim().toLowerCase();return applications.filter(a=>(filter==="All"||a.status===filter)&&(!q||a.company.toLowerCase().includes(q)||a.role.toLowerCase().includes(q)||a.notes.toLowerCase().includes(q)))},[applications,filter,query]);
 const stats=useMemo(()=>STATUSES.map(s=>({status:s,count:applications.filter(a=>a.status===s).length})),[applications]);
 return <section style={{padding:24,borderRadius:24,border:`1px solid ${border}`,background:bg,boxShadow:"0 18px 50px rgba(15,23,42,.06)"}}>
  <div><div style={{display:"flex",alignItems:"center",gap:8,color:"#7c3aed"}}><BriefcaseBusiness size={20}/><strong>Job application tracker</strong></div><p style={{margin:"7px 0 0",color:muted}}>Keep your applications, interviews, offers, and follow-ups organized.</p></div>
  {error&&<div style={{marginTop:12,padding:10,borderRadius:10,background:"rgba(239,68,68,.1)",color:"#b91c1c"}}>{error}</div>}
  <div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(150px,1fr))",gap:10,marginTop:16}}>{stats.map(x=><button key={x.status} onClick={()=>setFilter(x.status)} style={{padding:13,borderRadius:15,border:`1px solid ${filter===x.status?"#7c3aed":border}`,background:filter===x.status?"rgba(124,58,237,.12)":(dark?"rgba(30,41,59,.55)":"#f8fafc"),color:text,textAlign:"left",cursor:"pointer"}}><div style={{fontSize:12,color:muted}}>{x.status}</div><strong style={{fontSize:24}}>{x.count}</strong></button>)}</div>
  <div style={{display:"grid",gridTemplateColumns:"1.4fr .6fr",gap:10,marginTop:16}}><div style={{position:"relative"}}><Search size={16} style={{position:"absolute",left:12,top:13,color:muted}}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search company, role, or notes" style={{...input(dark),paddingLeft:38}}/></div><select value={filter} onChange={e=>setFilter(e.target.value as Status|"All")} style={input(dark)}><option>All</option>{STATUSES.map(s=><option key={s}>{s}</option>)}</select></div>
  <div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(180px,1fr))",gap:10,marginTop:12}}><Field placeholder="Company" value={company} onChange={setCompany} dark={dark}/><Field placeholder="Role" value={role} onChange={setRole} dark={dark}/><select value={status} onChange={e=>setStatus(e.target.value as Status)} style={input(dark)}>{STATUSES.map(s=><option key={s}>{s}</option>)}</select><input type="date" value={date} onChange={e=>setDate(e.target.value)} style={input(dark)}/><input placeholder="Notes (optional)" value={notes} onChange={e=>setNotes(e.target.value)} style={{...input(dark),gridColumn:"1/-1"}}/></div>
  <button onClick={add} style={{marginTop:11,border:0,borderRadius:11,background:"linear-gradient(135deg,#7c3aed,#2563eb)",color:"white",padding:"11px 15px",cursor:"pointer",fontWeight:800,display:"inline-flex",alignItems:"center",gap:7}}><CirclePlus size={16}/>Add application</button>
  <div style={{display:"grid",gap:9,marginTop:18}}>{loading?<div style={{padding:24,textAlign:"center",color:muted}}>Loading applications...</div>:filtered.length?filtered.map(a=><article key={a.id} style={{padding:15,border:`1px solid ${border}`,borderRadius:16,display:"grid",gridTemplateColumns:"1fr auto",gap:10}}><div><div style={{display:"flex",gap:8,alignItems:"center",flexWrap:"wrap"}}><strong style={{color:text}}>{a.role}</strong><select aria-label={`Status for ${a.company} ${a.role}`} value={a.status} onChange={e=>void updateStatus(a.id,e.target.value as Status)} style={{padding:"4px 8px",borderRadius:999,border:"1px solid rgba(124,58,237,.25)",background:dark?"#1e293b":"#f3efff",color:"#7c3aed",fontSize:11,fontWeight:800}}>{STATUSES.map(s=><option key={s}>{s}</option>)}</select></div><div style={{fontSize:13,color:muted,marginTop:3}}>{a.company} · {new Date(a.appliedAt).toLocaleDateString()}</div>{a.notes&&<p style={{fontSize:13,color:text,lineHeight:1.5,marginBottom:0}}>{a.notes}</p>}</div><button aria-label={`Delete ${a.company} ${a.role}`} onClick={()=>void remove(a.id)} style={{alignSelf:"start",border:`1px solid ${border}`,borderRadius:10,background:bg,color:muted,padding:8,cursor:"pointer"}}><Trash2 size={15}/></button></article>):<div style={{padding:24,textAlign:"center",color:muted}}>{applications.length?"No applications match your search.":"No applications yet. Add your first opportunity above."}</div>}</div>
  <div style={{display:"flex",alignItems:"center",gap:7,marginTop:12,fontSize:12,color:muted}}><CalendarDays size={14}/>Saved securely to your account.</div>
 </section>;
}
function Field({placeholder,value,onChange,dark}:{placeholder:string;value:string;onChange:(v:string)=>void;dark:boolean}){return <input placeholder={placeholder} value={value} onChange={e=>onChange(e.target.value)} style={input(dark)}/>}
const input=(dark:boolean):React.CSSProperties=>({width:"100%",boxSizing:"border-box",padding:11,border:`1px solid ${dark?"#475569":"#cbd5e1"}`,borderRadius:11,background:dark?"#020617":"#fff",color:dark?"#e5e7eb":"#0f172a",font:"inherit"});
