import { useState } from "react";
import { Copy, Sparkles, CheckCircle2, Lightbulb } from "lucide-react";

const API = import.meta.env.VITE_API_URL ?? "";
type Rewrite = { rewrittenText:string; improvements:string[]; keywordSuggestions:string[] };

export default function ResumeRewriter({ token }: { token: string }) {
  const [section,setSection]=useState("experience");
  const [targetRole,setTargetRole]=useState("");
  const [text,setText]=useState("");
  const [result,setResult]=useState<Rewrite|null>(null);
  const [loading,setLoading]=useState(false);
  const [error,setError]=useState("");
  const rewrite=async()=>{setError("");setResult(null);if(text.trim().length<10||targetRole.trim().length<2){setError("Enter your resume text and target role first.");return;}setLoading(true);try{const r=await fetch(`${API}/api/rewrite`,{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${token}`},body:JSON.stringify({section,text,targetRole})});const d=await r.json();if(!r.ok)throw new Error(d.error||"Unable to improve this section.");setResult(d);}catch(e){setError(e instanceof Error?e.message:"Unable to rewrite.");}finally{setLoading(false);}};
  return <section style={{marginTop:36}}><div style={{display:"flex",gap:10,alignItems:"center"}}><div style={{padding:9,borderRadius:10,background:"#f3e8ff"}}><Sparkles size={20}/></div><div><h2 style={{margin:0}}>AI Resume Rewriter</h2><p style={{margin:"4px 0",color:"#64748b"}}>Improve one section without inventing information.</p></div></div><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(300px,1fr))",gap:20,marginTop:18}}><div style={card}><label>Resume section</label><select value={section} onChange={e=>setSection(e.target.value)} style={input}><option value="summary">Professional Summary</option><option value="experience">Experience</option><option value="skills">Skills</option><option value="projects">Projects</option><option value="education">Education</option><option value="custom">Custom</option></select><label style={{display:"block",marginTop:14}}>Target role</label><input value={targetRole} onChange={e=>setTargetRole(e.target.value)} placeholder="e.g. Full Stack Developer" style={input}/><label style={{display:"block",marginTop:14}}>Original text</label><textarea value={text} onChange={e=>setText(e.target.value)} placeholder="Paste a bullet point, project description, experience section or professional summary..." style={{...input,minHeight:210,resize:"vertical"}}/><button onClick={rewrite} disabled={loading} style={button}>{loading?"Improving with AI...":"Improve with AI"}</button>{error&&<p style={{color:"#b91c1c"}}>{error}</p>}</div>{result&&<div style={card}><div style={{display:"flex",justifyContent:"space-between",gap:10,alignItems:"center"}}><h3 style={{margin:0}}>Improved version</h3><button onClick={()=>navigator.clipboard.writeText(result.rewrittenText)} style={copyButton}><Copy size={16}/> Copy</button></div><pre style={{whiteSpace:"pre-wrap",fontFamily:"inherit",lineHeight:1.7,marginTop:16}}>{result.rewrittenText}</pre><h3 style={{display:"flex",gap:7,alignItems:"center"}}><CheckCircle2 size={18}/> What improved</h3><ul>{result.improvements.map((x,i)=><li key={i}>{x}</li>)}</ul><h3 style={{display:"flex",gap:7,alignItems:"center"}}><Lightbulb size={18}/> Keyword suggestions</h3><div style={{display:"flex",gap:8,flexWrap:"wrap"}}>{result.keywordSuggestions.map((x,i)=><span key={i} style={{background:"#f1f5f9",padding:"6px 10px",borderRadius:999,fontSize:13}}>{x}</span>)}</div></div>}</div></section>;
}
const card:React.CSSProperties={background:"white",border:"1px solid #e2e8f0",borderRadius:18,padding:24,boxShadow:"0 8px 30px rgba(15,23,42,.04)"}; const input:React.CSSProperties={width:"100%",marginTop:7,padding:12,border:"1px solid #cbd5e1",borderRadius:10,font:"inherit"}; const button:React.CSSProperties={marginTop:16,border:0,borderRadius:10,background:"#0f172a",color:"white",padding:"12px 18px",fontWeight:700,cursor:"pointer"}; const copyButton:React.CSSProperties={border:"1px solid #cbd5e1",background:"white",padding:"7px 10px",borderRadius:8,display:"inline-flex",gap:6,alignItems:"center",cursor:"pointer"};
