import { useMemo, useState } from "react";
import { BrainCircuit, CheckCircle2, Copy, Search, Sparkles, Target, XCircle } from "lucide-react";

type Props={jobDescription:string;resumeText?:string;dark?:boolean};
const stop=new Set(["with","from","that","this","your","have","will","the","and","for","are","you","our","job","role","years","work","team","using","experience","skills"]);
const clean=(text:string)=>text.toLowerCase().replace(/[^a-z0-9+#.\-\s]/g," ").split(/\s+/).filter(w=>w.length>2&&!stop.has(w));
const title=(v:string)=>v.replace(/\b\w/g,c=>c.toUpperCase());

export default function SkillGapAnalyzer({jobDescription,resumeText="",dark=false}:Props){
 const[query,setQuery]=useState("");const[copied,setCopied]=useState(false);
 const data=useMemo(()=>{const job=clean(jobDescription);const resume=new Set(clean(resumeText));const freq=new Map<string,number>();job.forEach(w=>freq.set(w,(freq.get(w)||0)+1));const ranked=[...freq.entries()].sort((a,b)=>b[1]-a[1]||b[0].length-a[0].length).slice(0,30).map(([word,count])=>({word:title(word),count}));const matched=ranked.filter(x=>resume.has(x.word.toLowerCase()));const missing=ranked.filter(x=>!resume.has(x.word.toLowerCase()));return{matched,missing};},[jobDescription,resumeText]);
 const filter=(x:{word:string})=>x.word.toLowerCase().includes(query.toLowerCase());const copy=async()=>{await navigator.clipboard?.writeText(data.missing.map(x=>x.word).join(", "));setCopied(true);setTimeout(()=>setCopied(false),1600)};const bg=dark?"#0f172a":"#fff";const border=dark?"#334155":"#e2e8f0";const muted=dark?"#94a3b8":"#64748b";const coverage=data.matched.length+data.missing.length?Math.round(data.matched.length/(data.matched.length+data.missing.length)*100):0;
 return <section style={{marginTop:22,padding:22,borderRadius:24,border:`1px solid ${border}`,background:bg,boxShadow:"0 18px 50px rgba(15,23,42,.06)"}}><div style={{display:"flex",justifyContent:"space-between",gap:12,alignItems:"flex-start",flexWrap:"wrap"}}><div><div style={{display:"flex",gap:8,alignItems:"center",color:"#7c3aed"}}><BrainCircuit size={20}/><strong>Skill Gap Analyzer</strong></div><p style={{margin:"7px 0 0",color:muted}}>Compare job-description terms against your resume content.</p></div><button onClick={copy} disabled={!data.missing.length} style={button}><Copy size={16}/>{copied?"Copied":"Copy skill gaps"}</button></div><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(160px,1fr))",gap:12,marginTop:18}}><Metric icon={<Target size={17}/>} label="Keyword coverage" value={`${coverage}%`}/><Metric icon={<CheckCircle2 size={17}/>} label="Matched terms" value={data.matched.length}/><Metric icon={<XCircle size={17}/>} label="Skill gaps" value={data.missing.length}/></div><div style={{position:"relative",marginTop:18}}><Search size={16} style={{position:"absolute",left:13,top:13,color:muted}}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search skills and keywords..." style={{width:"100%",boxSizing:"border-box",padding:"12px 12px 12px 38px",border:`1px solid ${border}`,borderRadius:12,background:dark?"#020617":"#f8fafc",color:dark?"#e5e7eb":"#0f172a"}}/></div><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(260px,1fr))",gap:14,marginTop:16}}><Group title="Already covered" icon={<CheckCircle2 size={18}/>} items={data.matched.filter(filter)} empty="Add more resume content to calculate coverage." good dark={dark}/><Group title="Priority skill gaps" icon={<Sparkles size={18}/>} items={data.missing.filter(filter)} empty="No gaps found for this search." dark={dark}/></div></section>}
function Metric({icon,label,value}:{icon:React.ReactNode;label:string;value:string|number}){return <div style={{padding:15,borderRadius:17,background:"rgba(124,58,237,.08)"}}><div style={{display:"flex",gap:7,alignItems:"center",color:"#7c3aed",fontSize:13,fontWeight:700}}>{icon}{label}</div><strong style={{fontSize:27,display:"block",marginTop:7}}>{value}</strong></div>}
function Group({title,icon,items,empty,good,dark}:{title:string;icon:React.ReactNode;items:{word:string;count:number}[];empty:string;good?:boolean;dark:boolean}){return <div style={{padding:16,borderRadius:18,background:dark?"rgba(30,41,59,.6)":"#f8fafc"}}><h3 style={{margin:"0 0 12px",display:"flex",gap:8,alignItems:"center",fontSize:16,color:good?"#15803d":"#7c3aed"}}>{icon}{title}</h3>{items.length?<div style={{display:"flex",gap:8,flexWrap:"wrap"}}>{items.map(x=><span key={x.word} style={{padding:"7px 10px",borderRadius:999,border:`1px solid ${good?"#bbf7d0":"#ddd6fe"}`,background:dark?"#0f172a":"#fff",fontSize:13,fontWeight:650}}>{x.word}{x.count>1&&<small style={{opacity:.55}}> · {x.count}×</small>}</span>)}</div>:<p style={{margin:0,opacity:.6,fontSize:13}}>{empty}</p>}</div>}
const button:React.CSSProperties={border:0,borderRadius:12,padding:"10px 13px",cursor:"pointer",background:"#7c3aed",color:"white",fontWeight:800,display:"inline-flex",alignItems:"center",gap:7};
